'use client';

import { useState } from 'react';
import { ArrowRight, Globe2, Hotel, MapPin, Menu, MessageCircle, Plane, Ship, Sparkles, Users, X } from 'lucide-react';

const services: [string,string,React.ElementType][] = [
  ['Billetterie','Trouvez la solution aérienne adaptée à votre projet.',Plane],['Réservations d’hôtels','Un hébergement adapté à votre séjour.',Hotel],['Voyages organisés','Des programmes structurés pour voyager sereinement.',Globe2],['Voyages à la carte','Votre destination, votre rythme, votre expérience.',MapPin],['Omra','Programmes et informations pour préparer votre Omra.',Sparkles],['Croisières','Découvrez les possibilités de voyages en croisière.',Ship],['Séminaires & événements','Solutions pour groupes, colloques et conférences.',Users]
];
const destinations=['Paris','Istanbul','Dubai','Marrakech','Cairo','Rome','Barcelona','London','Makkah','Madinah'];
function wa(message:string){window.open(`https://wa.me/213560398890?text=${encodeURIComponent(message)}`,'_blank')}
export default function Home(){
 const[menu,setMenu]=useState(false),[ar,setAr]=useState(false),[sent,setSent]=useState(false),[service,setService]=useState('Billetterie');
 const t=ar?{nav:['الرئيسية','العروض','الوجهات','الخدمات','من نحن','اتصل بنا'],hero:'رحلتك تبدأ من هنا.',sub:'تذاكر الطيران، الفنادق، الرحلات المنظمة، الرحلات حسب الطلب، العمرة وخدمات السفر المصممة حسب احتياجاتك.',quote:'اطلب عرضك',services:'خدماتنا',destinations:'وجهات مختارة',about:'خبرة سفر منظمة، بمرافقة إنسانية',aboutText:'TTS Voyages هي وكالة سياحة وأسفار تقدم حلولاً في تذاكر الطيران والفنادق والرحلات المنظمة والرحلات حسب الطلب والعمرة والرحلات البحرية وتنظيم الفعاليات.',contact:'تواصل معنا'}:{nav:['Accueil','Nos offres','Destinations','Services','À propos','Contact'],hero:'Votre voyage commence ici.',sub:'Billetterie, hôtels, voyages organisés, voyages à la carte, Omra et solutions de voyage adaptées à vos besoins.',quote:'Demander un devis',services:'Nos services',destinations:'Destinations sélectionnées',about:'Un voyage pensé avec soin, de la demande au départ',aboutText:'TTS Voyages accompagne vos projets de voyage avec des services de billetterie, hôtels, voyages organisés, voyages à la carte, Omra, croisières et événements professionnels.',contact:'Parler à un conseiller'};
 return <main dir={ar?'rtl':'ltr'}>
 <header className="header"><a href="#top" className="brand"><img src="/tts-logo.svg" alt="TTS Voyages"/><span>Tlemsani Tours<small>TTS VOYAGES</small></span></a><nav>{t.nav.map((n,i)=><a key={n} href={['#top','#offers','#destinations','#services','#about','#contact'][i]}>{n}</a>)}</nav><div className="actions"><button className="lang" onClick={()=>setAr(!ar)}>{ar?'FR':'العربية'}</button><button className="wa" onClick={()=>wa('Bonjour TTS Voyages, je souhaite avoir des informations sur un voyage.')}><MessageCircle size={17}/> WhatsApp</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 {menu&&<div className="mobileMenu">{t.nav.map((n,i)=><a key={n} href={['#top','#offers','#destinations','#services','#about','#contact'][i]} onClick={()=>setMenu(false)}>{n}</a>)}<button onClick={()=>setAr(!ar)}>{ar?'Français':'العربية'}</button></div>}
 <section id="top" className="hero"><div className="heroBg"/><div className="heroContent"><span className="eyebrow">TTS VOYAGES · AGENCE DE VOYAGES ET TOURISME</span><h1>{t.hero}</h1><p>{t.sub}</p><div className="heroBtns"><a className="primary" href="#offers">{t.quote}<ArrowRight size={18}/></a><button className="secondary" onClick={()=>wa('Bonjour TTS Voyages, je souhaite demander un devis.')}><MessageCircle size={18}/> Parler sur WhatsApp</button></div></div><div className="inquiry"><div className="tabs">{['Vol','Hôtel','Voyage','Omra','Visa','Sur mesure'].map(x=><button key={x} className={service===x?'active':''} onClick={()=>setService(x)}>{x}</button>)}</div><div className="fields"><label>Destination<input placeholder={service==='Vol'?'Paris, Istanbul…':'Votre destination'}/></label><label>Date<input type="date"/></label><label>Voyageurs<input type="number" min="1" placeholder="2"/></label><button className="primary" onClick={()=>setSent(true)}>Demander un devis</button></div></div></section>
 {sent&&<div className="modal"><div className="modalCard"><button className="close" onClick={()=>setSent(false)}><X/></button><Sparkles size={28}/><h2>Votre demande est prête</h2><p>Pour obtenir une réponse personnalisée, envoyez votre demande directement à TTS Voyages sur WhatsApp.</p><button className="primary" onClick={()=>wa(`Bonjour TTS Voyages, je souhaite un devis pour ${service}.`)}>Continuer sur WhatsApp <ArrowRight size={17}/></button></div></div>}
 <section id="services" className="section"><div className="sectionHead"><span className="eyebrow">TTS VOYAGES</span><h2>{t.services}</h2><p>Des solutions simples pour organiser votre prochain déplacement.</p></div><div className="serviceGrid">{services.map(([title,desc,Icon])=><article className="service" key={title}><div className="icon"><Icon size={22}/></div><h3>{title}</h3><p>{desc}</p><a href="#contact">Découvrir <ArrowRight size={15}/></a></article>)}</div></section>
 <section id="offers" className="darkSection"><div className="sectionHead light"><span className="eyebrow">NOS OFFRES</span><h2>Des voyages qui vous ressemblent.</h2><p>Découvrez nos possibilités et demandez les informations disponibles auprès de l’agence.</p></div><div className="offerGrid"><article className="offer large"><div className="photo paris"/><div><span>VOYAGE ORGANISÉ</span><h3>Partez l’esprit tranquille.</h3><p>Programme, hébergement, transport et accompagnement selon l’offre retenue.</p><a href="#contact">Demander les détails <ArrowRight size={16}/></a></div></article><article className="offer"><div className="photo makkah"/><div><span>OMRA</span><h3>Votre Omra, une expérience préparée avec soin.</h3><p>Omra depuis 1994 · Programmes et informations sur demande.</p><a href="#contact">Découvrir l’Omra <ArrowRight size={16}/></a></div></article><article className="offer"><div className="photo cruise"/><div><span>CROISIÈRES</span><h3>Prenez le large.</h3><p>Découvrez les possibilités de voyage en croisière proposées par l’agence.</p><a href="#contact">Nous consulter <ArrowRight size={16}/></a></div></article></div></section>
 <section id="destinations" className="section"><div className="sectionHead"><span className="eyebrow">INSPIRATION</span><h2>{t.destinations}</h2><p>Destinations de démonstration — disponibilité et tarifs sur demande.</p></div><div className="destinationGrid">{destinations.map((d,i)=><article key={d} className={`destination d${i}`}><div><span>DESTINATION</span><h3>{d}</h3><button onClick={()=>wa(`Bonjour TTS Voyages, je souhaite des informations pour ${d}.`)}>Explorer <ArrowRight size={15}/></button></div></article>)}</div></section>
 <section id="about" className="split"><div><span className="eyebrow">POURQUOI TTS VOYAGES ?</span><h2>{t.about}</h2><p>{t.aboutText}</p><div className="checks"><span>✓ Accompagnement personnalisé</span><span>✓ Plusieurs services de voyage</span><span>✓ Solutions adaptées</span><span>✓ Contact direct</span></div></div><div className="experience"><span>OMRA</span><strong>depuis 1994</strong><small>Information visible dans la référence fournie — à confirmer officiellement avant publication finale.</small></div></section>
 <section id="contact" className="contact"><div><span className="eyebrow">CONTACT</span><h2>{t.contact}</h2><p>Décrivez votre projet. Nous vous orientons vers la solution adaptée.</p><div className="phones"><a href="tel:+213560398890">0560 39 88 90</a><a href="tel:+213661345767">0661 34 57 67</a></div></div><div className="contactCard"><label>Nom complet<input placeholder="Votre nom"/></label><label>Téléphone<input placeholder="05 / 06…"/></label><label>Service<select><option>Billetterie</option><option>Hôtel</option><option>Voyage organisé</option><option>Voyage à la carte</option><option>Omra</option><option>Croisière</option><option>Séminaire / événement</option></select></label><label>Message<textarea placeholder="Parlez-nous de votre projet…"/></label><button className="primary" onClick={()=>wa('Bonjour TTS Voyages, je souhaite vous contacter au sujet de mon projet de voyage.')}>Envoyer via WhatsApp <MessageCircle size={17}/></button></div></section>
 <footer><div className="brand"><img src="/tts-logo.svg" alt="TTS Voyages"/><span>Tlemsani Tours<small>Agence de voyages et tourisme</small></span></div><p>© 2026 Tlemsani Tours · TTS Voyages</p><button onClick={()=>wa('Bonjour TTS Voyages.')}>WhatsApp <MessageCircle size={16}/></button></footer><a className="floatingWa" onClick={()=>wa('Bonjour TTS Voyages, je souhaite avoir des informations.')}><MessageCircle/></a>
 </main>
}